### ISSUE TITLE
Typo in Page 88 and Page 98

### ISSUE THREAD

**Issue by AaronYang15** [gamma-opt/optimisation-notes#36]
1. In the page 88, the nonnegative constraint for the first problem should be $x_1, x_2 \geq 0$, instead of $x_1, x_2, x_3, x_4 \geq 0$.
2. In the page 98, the term in the first fomulation should be $e_l$ instead of $e_i$. Moreover, adding the explantion that $e_l$ is an $m$ dimension vector will be heplful to understand.

**Comment by FabsOliveira** [comment]
Many thanks @AaronYang15! Those have been fixed now
